version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/" # Specify the directory containing the requirements.txt file
    #file: "requirements.txt" # Specify the dependency file
    schedule:
      interval: "weekly"
