---
version: '3.6'
services:
  pac-tester:
    image: lucasnz/pac-tester
    container_name: pac-tester
    environment:
      TZ: Pacific/Auckland
    restart: always
    healthcheck:
      test: ["CMD", python", "web-test.py", "--url", "http://localhost:5000/", "--method", "HEAD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s