---
version: '3.6'
services:
  pacparserweb:
    image: lucasnz/pacparserweb
    container_name: pacparserweb
    environment:
      TZ: Pacific/Auckland
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-S", "--spider", "http://127.0.0.1:5000/", "-O/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s